### ISSUE TITLE
Allow generating `setf`s for generics in `define-generic`

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nclasses#17]
`define-generic` is quite good already, but there's one case in Nyxt that it doesn't cover: generation of FFI generics with `setf`s for them. So we need to be able to do something like:
``` lisp
(define-generic foo ((a integer) (b integer) (c integer))
  (/ (+ a b) c)
  (:generate-setf-p t))
```
Which, amongs other things, would expand to both 
``` lisp
(defgeneric foo (a b c)
  (:method ((a integer) (b integer) (c integer))
    (/ (+ a b) c)))
```
and 
``` lisp 
(defgeneric (setf foo) (value a b c))
```

I'm set to implement this feature someday, but I have several implementation details that I'm unsure about:
- Should we generate `setf` function always empty or do we somehow set a default method for it?
- How do we call this option? I don't like `:generate-setf-p` because it feels inconsistent with the rest of things.
- Should we add a global variable for this? I'd say no, because the behavior might be quite unintuitive and destructive (= undefining already created `setf` generics).

**Comment by Ambrevar** [comment]
Wait, what's the point of generating 

```lisp
(defgeneric (setf foo) (value a b c))
```
?


> * Should we generate `setf` function always empty or do we somehow set a default method for it?

What could possibly be a reasonable default?  Not sure there is one.

> * How do we call this option? I don't like `:generate-setf-p` because it feels inconsistent with the rest of things.

What about `setf-method-p`?

> * Should we add a global variable for this? I'd say no, because the behavior might be quite unintuitive and destructive (= undefining already created `setf` generics).

Fine without global.

**Comment by Ambrevar** [comment]
Yes, that would work.

That said, what are the benefits in your opinion?

**Comment by aartaka** [comment]
> That said, what are the benefits in your opinion?

This saves us _duplicate_ code lines (`define-generic foo (a b c)` and `define-generic (setf foo) (value a b c)`). Their duplication means that it's easier for them to go off-sync (lots of instances of that in Nyxt) or get slightly broken with typos. Having a single declaration generating duplicate code would ensure the consistency of both a regular generic and `setf` version.

It also allows us to kind of generate shorthand getters and setters like conventional languages (e.g. C#) allow, but with multiple dispatch :)

**Comment by Ambrevar** [comment]
I'm not too convinced by the argument of deduplication: the lines are not really the same.
Plus even in the case of a `:method` or `:setf` option, we would need to repeat the lambda-list in any case.

**Comment by aartaka** [comment]
Yes, that's a good one. I'm leaning towards not having it either.
