### ISSUE TITLE
Flatted/inline slots

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nclasses#19]
So we mostly stick to the overall structure of `defclass` with our `define-class`, which is cool. but then there's an extra layer of parentheses to slot definitions we have:
``` lisp
(define-class name ()
  ((slot-a 5)
   (slot-b 8)))
```
While this is consistent with historic form, it would be cool to drop this extra layer. Several problems with it:
- It becomes much harder to distinguish `(slot-a 5)` and `(slot-a slot-b slot-c)`. Maybe even impossible.
- We lose an additional layer of indentation separating slots from options, which was visually useful.

I'm extremely uncertain about this, but if we make it deterministic enough, then why not have it?

**Comment by Ambrevar** [comment]
Another point:

- How to you distinguish options from slots?  Could check if first element is a keyword or a symbol, but we should see what the standard allows here.

**Comment by aartaka** [comment]
> * How to you distinguish options from slots?  Could check if first element is a keyword or a symbol, but we should see what the standard allows here.

Keyword checking is safe, I guess. [`defclass` doc](https://cl-community-spec.github.io/pages/defclass.html) says:
```
Slot-name--a symbol. The slot-name argument is a symbol that is syntactically valid for use as a variable name. 
```

And then, keywords cannot be variables, at least. Spinneret uses keywords as macro names, and you can `defun` a keyword function, which is not cool, but slot name... I'm not sure—keywords are not valid `boundp` variable names, at least (҂⌣̀_⌣́)

**Comment by aartaka** [comment]
Closing as not-implementable-reliably then.
